FROM python:3.11

RUN mkdir -p /var/opt/wgconfiggen

ADD https://api.github.com/repos/$USER/$REPO/git/refs/heads/$BRANCH version.json
RUN git clone --depth=1 -b $BRANCH https://github.com/$USER/$REPO.git /var/opt/wgconfiggen

WORKDIR /var/opt/wgconfiggen

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt 

CMD ["gunicorn" "-w" "4" "wireguardConfigApp:app" "-b" "0.0.0.0:80"]
